### ISSUE TITLE
@delete http://localhost:8080/game-rewrite/invite-gameでserver errorが発生している

### ISSUE THREAD

**Issue by Jack-in-42Tokyo** [Shuta-syd/42-ft_transcendence#354]

**Comment by Jack-in-42Tokyo** [comment]
下記のようなエラーが発生していました。(InviteGameに関してのみで、randomGameの方は問題ありませんでした。)
backend  | [Nest] 91  - 05/04/2023, 1:59:07 AM   ERROR [ExceptionsHandler]
backend  | Invalid `this.prisma.inviteGame.findUnique()` invocation in
backend  | /backend/dist/game/rewrite/game-rewrite.controller.js:60:51
backend  |
backend  |   57     });
backend  |   58 }
backend  |   59 async deleteInviteGame(req, data) {
backend  | → 60     const room = await this.prisma.inviteGame.findUnique({
backend  |            where: {
backend  |          ?   id?: String,
backend  |          ?   player1?: String,
backend  |          ?   player2?: String
backend  |            }
backend  |          })
backend  |
backend  | Argument where of type InviteGameWhereUniqueInput needs at least one argument. Available args are listed in green.
backend  |
backend  | Note: Lines with ? are optional.
backend  |
backend  | Error:
backend  | Invalid `this.prisma.inviteGame.findUnique()` invocation in
backend  | /backend/dist/game/rewrite/game-rewrite.controller.js:60:51
backend  |
backend  |   57     });
backend  |   58 }
backend  |   59 async deleteInviteGame(req, data) {
backend  | → 60     const room = await this.prisma.inviteGame.findUnique({
backend  |            where: {
backend  |          ?   id?: String,
backend  |          ?   player1?: String,
backend  |          ?   player2?: String
backend  |            }
backend  |          })
backend  |
backend  | Argument where of type InviteGameWhereUniqueInput needs at least one argument. Available args are listed in green.
backend  |
backend  | Note: Lines with ? are optional.
backend  |
backend  |     at mi.validate (/backend/node_modules/@prisma/client/runtime/library.js:149:91)
backend  |     at tn.createMessage (/backend/node_modules/@prisma/client/runtime/library.js:166:1205)
backend  |     at /backend/node_modules/@prisma/client/runtime/library.js:179:10962
backend  |     at runInChildSpan (/backend/node_modules/@prisma/client/runtime/library.js:70:25817)
backend  |     at PrismaService._executeRequest (/backend/node_modules/@prisma/client/runtime/library.js:179:10951
